---
abstract: 'Prints modules used by your script when your script ends'
author:
  - 'Christian Renz <crenz@web42.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-PrintUsed
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
resources:
  repository: http://github.com/crenz/Module-PrintUsed
version: '0.06'
