--- #YAML:1.0
name:               Module-PrintUsed
version:            0.06
abstract:           Prints modules used by your script when your script ends
author:
    - Christian Renz <crenz@web42.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
resources:
    repository:  http://github.com/crenz/Module-PrintUsed
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
